### ISSUE TITLE
Add support to select TitleBar area based of input widget

### ISSUE THREAD

**Issue by Detector-I** [wangwenx190/framelesshelper#102]
Hey thank you for great project, there is just one thing that I think is missing, looks like currently program will use top side of program as Title Bar all the time, although we can adjust its size some times its not enough, it would be much better if we can set a QWidget or QFrame as Title Bar
```c++
FramelessWindowsManager::setTitleBar(win, ui.title_bar);
```
it could help in lots of situation, like when the program have custom title bar that not fill the top side entirely... (like when there is some other widget beside it, I know we can ignore them with `setHitTestVisible` but still, having this is better) or when there is some padding between top and the title bar itself...
something like what this project done in past [Qt-Nice-Frameless-Window](https://github.com/Bringer-of-Light/Qt-Nice-Frameless-Window)

**Comment by wangwenx190** [comment]
Hi, sorry for the late reply. I'm currently working on a wip branch which will become the 2.x version, in the new code, I added this functionality for convenience. And there are many improvements to the Windows implementation, due to large architechtural change, these improvements won't be cherry-picked back to the 1.x branch.

**Comment by wangwenx190** [comment]
Thanks for your suggestion, it's really a good and convenient feature indeed.

**Comment by wangwenx190** [comment]
Implemented in 2.0
