### ISSUE TITLE
VS2019+QT5.15.2 : C4127 is a little annoying

### ISSUE THREAD

**Issue by kylix** [wangwenx190/framelesshelper#123]
A simple solution is to change /W4 to /W3 in CMakeLists.txt, otherwise it will halt the building.
Is the problem only related to VS2019 ? 
I also replace the code in framelesswindowsmanager.cpp at 101 with:
```
        QDir dir(QCoreApplication::applicationDirPath());
        const QString iniFilePath = dir.filePath(kConfigFileName);

```
I think is a more 'native' for Qt.

**Comment by wangwenx190** [comment]
I'm using VS2022 and doesn't get any warnings when building. I think the best solution would be fix the warning instead of lower the warning level. Can you make a PR if you are willing to fix the warning? Or you can tell me how to fix your warning and let me push new code.

```
I also replace the code in framelesswindowsmanager.cpp at 101 with:
```
Looks good to me. Can you make a PR for this? Thanks!

**Comment by wangwenx190** [comment]
Thanks!

**Comment by wangwenx190** [comment]
OK, another user tell me about this issue, it seems lower the warning level is the best option.
