### ISSUE TITLE
[Feature Request] close / maximize / minimize buttons position

### ISSUE THREAD

**Issue by micpub** [wangwenx190/framelesshelper#127]
Hello,
we have plans to switch from our 'qml / qt' based csd implementation to this lib - however we are missing an ability to change the position of close / maxi / mini buttons  to either left or right of the app window.
we currently support such thing - by default on windows we place it on the right /// mac - left /// linux - left

on the right the buttons are ( mini / maxi / close)
on the left (close/ mini / maxi)
in the case where our default is 'wrong' (linux distros can have it on the left / right) we have a combobox in the options with the ability to manually switch to either left / right.

it would be nice to have it here too.

----
the item containing these buttons also should be exposed to the qml via property - so we could position other items to it (anchors).

**Comment by wangwenx190** [comment]
OK, that's a sensible suggestion.

But currently the system buttons are provided mostly for demenstration purposes because they now look and behave just like the native system buttons, this may not fit every application's needs, so I thought maybe they are not useful for developers because most applications have their own style of system buttons. And for the 2.0 version of this project, it's now possible to set a title bar widget/item for the frameless window, so if you use your own homemade title bar, I guess there's not much difficulty to achieve what your said above?

Anyway, currently I'm working on the 2.1 version and in this version, some large refactors have been made, that including the redesign of the standard title bar provided by FramelessHelper, the system buttons are also exposed to outside through Q_PROPERTYs, so you may be able to do something to these buttons.

And due to the contents of the 2.1 version is very different with what I initially planned, I decided to release the 2.1 version as early as possible, instead of waiting for some features which are not urgent.

**Comment by micpub** [comment]
ok maybe ive 'misunderstood' some things - i'll look again at it once 2.1 is out

thanks

**Comment by wangwenx190** [comment]
I hope I can release the 2.1 version later this week, if things go smoothly :)
