### ISSUE TITLE
Changing the blur color

### ISSUE THREAD

**Issue by mirroI** [wangwenx190/framelesshelper#147]
Is it possible to add functionality so that I can choose what color the blur will be, dark or light. Linking to the theme of the system is not convenient.

**Comment by wangwenx190** [comment]
It's totally possible, and I also left some interfaces to do that. I didn't expose such functionalities publicly because there has not been any user request for such features.

**Comment by wangwenx190** [comment]
But I need to know your platform (name & version) and Qt version. On some platforms there will be some limitations.

**Comment by mirroI** [comment]
Windows 10, 11 platform, qt version 6.3.1

**Comment by wangwenx190** [comment]
OK, thanks.

For the current version, FramelessHelper will enable the MICA material on Windows 11 and macOS and we can't control the tint color of it due to the OS doesn't expose any public interface to do that. But FramelessHelper also supports using pure software emulated blur effect, which we can control the tint color and tint opacity. But sadly the software emulated one doesn't look exactly the same with the OS provided one, and it also consumes more CPU and memory due to it's not hardware accelerated. So you'll have to choose which solution do you prefer.

And your feature request is too brief, can you give me some more detailed information about what function/interface do you expect? It will be much better if you can show me a prototype of the new interface you would expect.

**Comment by mirroI** [comment]
Thanks for the explanation, then most likely I will abandon this idea
