### ISSUE TITLE
[Qt Quick] When top-level Window has transparency, white line appears on top of window

### ISSUE THREAD

**Issue by midnightprioriem** [wangwenx190/framelesshelper#43]
When transparency is enabled on the top-level QML Window, a white line appears at the top of the window frame.

![Capture](https://user-images.githubusercontent.com/6120081/109879218-4eb3ee80-7c43-11eb-9436-a6edee2bd524.PNG)

```qml

Window {
    id: window
    visible: true
    width: 800
    height: 600
    title: qsTr("Hello, World!")
    color: "transparent"
    flags: Qt.Window


    FramelessHelper {
        id: framelessHelper
    }

        Row {
            anchors.top: parent.top
            anchors.right: parent.right

            MinimizeButton {
                id: minimizeButton
                onClicked: window.showMinimized()
                Component.onCompleted: framelessHelper.addIgnoreObject(
                                           minimizeButton)
            }

            MaximizeButton {
                id: maximizeButton
                maximized: window.visibility === Window.Maximized
                onClicked: {
                    if (maximized) {
                        window.showNormal()
                    } else {
                        window.showMaximized()
                    }
                }
                Component.onCompleted: framelessHelper.addIgnoreObject(
                                           maximizeButton)
            }

            CloseButton {
                id: closeButton
                onClicked: window.close()
                Component.onCompleted: framelessHelper.addIgnoreObject(
                                           closeButton)
            }
        }


    Component.onCompleted: {
        framelessHelper.setWindowFrameVisible(false)
        framelessHelper.removeWindowFrame(true)
        framelessHelper.setBlurEffectEnabled(true);
    }
}

```

With blur effect turned off, the issue still occurs. Only fixes I've found are setting ```flags = Qt.FramelessWindowHint``` which removes the window shadows and breaks Aero snapping, or using a Window color with no transparency at all.

**Comment by wangwenx190** [comment]
>
> Only fixes I've found are setting `flags = Qt.FramelessWindowHint`
>
Don't use `Qt::FramelessWindowHint` on **Windows**. It will break everything.

https://github.com/wangwenx190/framelesshelper/blob/310b44b8c461ff5007ab5da9f1d30e78383734c6/winnativeeventfilter.cpp#L785

Can you check whether change this line to `margins = {-1, -1, -1, -1};` can fix this issue or not?

**Comment by midnightprioriem** [comment]
> Can you check whether change this line to margins = {-1, -1, -1, -1}; can fix this issue or not?

My bad, should have mentioned I tried that already with this result:

![Capture](https://user-images.githubusercontent.com/6120081/109900772-e62a3900-7c65-11eb-8602-b01d0fcb181f.PNG)

**Comment by wangwenx190** [comment]
That white line is the original window frame provided by the system. If you use `margins = {1, 1, 1, 1};` you'll get four white lines which may be better than just one line. If you use `margins = {0, 0, 0, 0};` you can remove all white lines, but the frame shadow will get lost at the same time.

**Comment by wangwenx190** [comment]
If you don't care about the frame shadow, you can try `margins = {0, 0, 0, 0};`, this will not break Aero snapping.

**Comment by midnightprioriem** [comment]
> If you don't care about the frame shadow, you can try margins = {0, 0, 0, 0};, this will not break Aero snapping.

That works, thanks! Just to clarify for any future readers, I changed lines 784-786:

```
    if (!reset) {
        margins.cyTopHeight = 0;
    }
```

Is there a way to change the window frame color? I wouldn't mind having the margin shown if I could set them to a dark color. That would be a good solution.

**Comment by wangwenx190** [comment]
>
> Is there a way to change the window frame color?
>
The window frame is provided by the system, not me, so it can be changed by the user's own settings. I'm not sure how to change it in Windows 7/8/8.1, but for Windows 10, you can use "settings -> personalize -> color", and select show color on TitleBar/WindowFrame/TaskBar (don't remember the names correctly). If you really want to control the color from the application, the only way is to hide the whole window frame and draw one yourself.

**Comment by midnightprioriem** [comment]
Another update on this: You can actually hide the top border that get's drawn from within QML. If I add something like this:

```
    Rectangle
    {
        anchors.top: parent.top
        anchors.left: parent.left
        anchors.right: parent.right
        height: .5
        color: "#3d3636"
    }
```

I get this result, which looks much better than the white and still retains window shadows.

![Capture](https://user-images.githubusercontent.com/6120081/109969512-fe2fa600-7cc1-11eb-9407-6f19490be3a1.PNG)

**Comment by wangwenx190** [comment]
But only have one top border looks quite weird, I'd prefer have all four borders or get rid of all of them.

**Comment by midnightprioriem** [comment]
Sure, having all 4 borders works too, and looks acceptable.

```
    Rectangle
    {
        anchors.fill: parent
        color: "transparent"
        border.width: .5
        border.color: "#3b3642"
    }
```

![Capture](https://user-images.githubusercontent.com/6120081/109971042-c88bbc80-7cc3-11eb-9a47-552c0cc468a9.PNG)

Having the ability to set the margins from the frameless helper would be nice to leave it up to the developer on how to handle it.

**Comment by wangwenx190** [comment]
>
> Having the ability to set the margins from the frameless helper would be nice to leave it up to the developer on how to handle it.
>
Sounds reasonable, I'll try to implement something like that.

**Comment by wangwenx190** [comment]
>
> You can actually hide the top border that get's drawn from within QML
>
I remember I can't draw anything on top of the window frame, are you sure you are not using `margins = {0, 0, 0, 0};`?

**Comment by wangwenx190** [comment]
Can you test the latest code? The blur effect has been updated to the Acrylic Effect, and you can set a custom window frame now, for both Qt Widgets and Qt Quick.

**Comment by wangwenx190** [comment]
I'm closing this issue because I think it's not valid anymore. Feel free to re-open it or open a new issue if you find something wrong.

**Comment by midnightprioriem** [comment]
Yep, I'm okay with this story being closed out. I tested the latest code and the acrylic effect seems really messed up. It looks like it's a static blurry image of the desktop that is not updating live (tested using the Quick demo).

**Comment by wangwenx190** [comment]
> Yep, I'm okay with this issue being closed out. I tested the latest code and the acrylic effect seems really messed up. It looks like it's a static blurry image of the desktop that is not updating live (tested using the Quick demo).

Yes because I changed the way of how the window blur. Previously, I was using the undocumented API `SetWindowCompositionAttribute` to let the window become semi-transparent on Win10. If you see some kind of gradient color, it must be draw manually in Qt, not something achieved by that API. But actually I want to achieve something like the Acrylic blur introduced in Win10, not some kind of traditional DWM blur. That API can enable Acrylic blur for Win32 apps but it has critical issues so in fact it is totally not usable at all. So I have to emulate the Acrylic blur myself. In my point of view, the new blur effect has a better appearance, although we can't see what's behind the window indeed (the background won't update). If you want to use the original blur effect, just set the environment variable `_FRAMELESSHELPER_FORCE_DWM_BLUR` or `_FRAMELESSHELPER_FORCE_DISABLE_WALLPAPER_BLUR` to `1` or `true` and restart the application.

**Comment by wangwenx190** [comment]
Feel free to write more comments or open a new issue if you have different opinions.

**Comment by midnightprioriem** [comment]
That explanation makes sense, and I can certainly appreciate shooting for an acrylic effect that matches the standard Win10 appearance. In my opinion though, at least in their current states, the DWM blur is much better simply due it actually being dynamic. I'm not terribly concerned with giving my application a completely "native" feel, though, either.

**Comment by wangwenx190** [comment]
>
>  In my opinion though, at least in their current states, the DWM blur is much better simply due it actually being dynamic.
>
Yes, it's absolutely dynamic. But it's just a simple semi-transparent effect, beautiful, but not impressive, the Acrylic blur is far more artistic I think.

Originally, we could use the undocumentated API to enable Acrylic blur for Win32 apps and it works perfectly in some period of time, however, after some versions of Win10, it becomes very buggy and totally not usable. Some people report this bug to Microsoft about 1.5 or even 2 years ago, however, MS doesn't seem to want to fix it. But emulating the Acrylic blur is far more complicated because we have many difficutiles in acquiring what's behind the window (the image) and how to draw it in a high performance way. The easiest way is to do a static wallpaper blur like what this repo do now. It looks almost exactly the same with the official Acrylic blur but sadly it won't update dynamically indeed.

**Comment by wangwenx190** [comment]
@midnightprioriem Hi, the code just got updated. Now even if we are using the wallpaper blur, the window background can still be updated dynamically. Can you test the latest code to see whether it meets your needs?

**Comment by wangwenx190** [comment]
>
> Electron is an entirely different beast than Qt
>
Doesn't matter. It's native Win32 techniques, have nothing to do with Qt.

>
> Something else I'm missing in the latest implementation is the ability to have full control over the color blurred window. It seems that it adds a white overlay. I liked the ability in the past to leave the window completely transparent with the blur effect, then create my own tints within the app itself, or set the tint in the frameless helper.
>
Yes, it's a cool feature. Currently the only problem is a white overlay is added unconditionally, I'll add an option for the user to remove that overlay within these days. You can set the tint color as before.

**Comment by wangwenx190** [comment]
>
> Is the DWM blur method you were using similar/the same as the implementation for electron's vibrancy module? I did find another electron package that builds on vibrancy but adds the acrylic effect here
>
Thanks for sharing these repos! I've now finished reading their source code. Unfortunatally, they are using the undocumentated API `SetWindowCompositionAttribute` as well, it has a severe bug so I can't use it. That two repos that depend on that API are also affected. That's why I'm seeking for a solution of emulating the Acrylic blur myself. But doesn't matter, the Acrylic blur is only available on Win10, I'm thinking using xaml island to bring the real Acrylic brush to Qt applications.

**Comment by wangwenx190** [comment]
Hi, the code just got updated. Now you can set the environment variable `_FRAMELESSHELPER_DISABLE_EXTRA_PROCESS_FOR_BLUR` to restore to previous behavior. Once you set that env variable, this repo won't do any extra processing but only makes the window semi-transparent. Setting this flag will also disable wallpaper blur because bluring the wallpaper is part of the "extra processing".

**Comment by wangwenx190** [comment]
One small hint: the `removeWindowFrame()` function is removed because it only exists for testing purposes. Normal users should not depend on it to develop applications. You can draw the window frame yourself, as what you have done.
