### ISSUE TITLE
pos() returns negative coordinates when QMainWindow is maximised

### ISSUE THREAD

**Issue by JulienMaille** [wangwenx190/framelesshelper#59]
Do you have any idea why `pos()` returns `(-1, -4)` when maximised? When restoring position on next launch, `move()` fails to work with the negative QPoint .

**Comment by wangwenx190** [comment]
On Windows, if a window is maximized, it will actually become a bit larger than the screen so you will not be able to resize it from its edges. It sounds weired but it's the truth. But I'm not sure whether it's related to this issue or not. For framelesshelper, I applied custom window margin to the window so Qt _may_ report wrong coordinate when window is maximized.

**Comment by JulienMaille** [comment]
How can I correct that by substracting the right margins from position? Currently it breaks the common way to save/restore QMainWindow size and position.

**Comment by wangwenx190** [comment]
For FramelessHelper, the custom window margin is applied by this function:
https://github.com/wangwenx190/framelesshelper/blob/28144b1e74f6f4f774d59f51f5402a8fa4b061e5/utilities_win32.cpp#L387
In your case, you just need to reset custom window margin when the window is maximized and apply it again when the window is restored. Although calling `Utilities::updateQtFrameMargins(window, false)` means restore custom window margin to Qt's default value, I'm not sure it won't break frameless windows. You can try different margin values to see which one is correct. I suggest not modify this function but write a function yourself and do changes in your own function, because modify `Utilities::updateQtFrameMargins` itself may affect FramelessHelper's behavior.

**Comment by JulienMaille** [comment]
Commenting `Utilities::updateQtFrameMargins()` or changing the values in `const QMargins margins = {-bw, -tbh, -bw, -bh};` does not modify the result of `pos()` when maximized. Am I doing it wrong?

**Comment by wangwenx190** [comment]
@JulienMaille  Hi, have you solved this issue? Is the issue still exist? I've seen several commits to modify the window frame judgement in Windows QPA recently merged in Qt dev branch, maybe situation can improve.

**Comment by JulienMaille** [comment]
Well I don't have issues with window positioning anymore

**Comment by JulienMaille** [comment]
Hmm there might be a small bug, I need to investigate.
If you work with `restoreState()` `restoreGeometry()` and close you app in windowed mode but with the window near the top of the screen, it seems that it will be then restore at a slightly different position further away from the top

**Comment by wangwenx190** [comment]
Does this issue still exist in the latest 2.0 code?

**Comment by JulienMaille** [comment]
Nope

**Comment by wangwenx190** [comment]
OK, closed
