### ISSUE TITLE
设置较小的边框高度后，窗口 "最大化" 会导致顶端被剪切

### ISSUE THREAD

**Issue by altairwei** [wangwenx190/framelesshelper#77]
我想将 resize indicator 的显示范围缩小一点，避免挡住 UI 边缘的控件，所以我设置了：

```C++
__flh_ns::FramelessWindowsManager::setResizeBorderHeight(win, 2);
```

然而这在 Windows 端导致了一个问题：窗口全屏后顶部有一部分 UI 被剪切掉了。见图：

~~全屏前~~ 最大化前：

![Snipaste_2021-08-16_22-17-40](https://user-images.githubusercontent.com/30854075/129578542-d911e5bf-c0f7-471c-9817-75dec0011fcd.png)

~~全屏后~~ 最大化后：

![Snipaste_2021-08-16_22-17-28](https://user-images.githubusercontent.com/30854075/129578573-0e335990-061e-4fbb-837a-699161eb6f64.png)

我测试了一下 `setResizeBorderWidth` 也有类似问题。

**Comment by wangwenx190** [comment]
还是linux平台吧

**Comment by altairwei** [comment]
> 还是linux平台吧

Windows 平台，不过我还需要再测试下 examples 中的例子，确保不是我的应用造成的。

**Comment by altairwei** [comment]
我测试了一下 Windows 平台的 examples/mainwindow 程序，确实存在我提到的问题。注意截图中全屏模式下的左边界被剪切掉了一部分。

![Snipaste_2021-08-17_22-25-51](https://user-images.githubusercontent.com/30854075/129744297-d6462aa8-8f45-4e57-87c0-dd9ca85ae8a4.png)

**Comment by wangwenx190** [comment]
你提到 Windows、全屏，我已经知道问题在哪了，是最近造成的regression





------------------ 原始邮件 ------------------
发件人: Altair Wei ***@***.***&gt;
发送时间: 2021年8月17日 22:27
收件人: wangwenx190/framelesshelper ***@***.***&gt;
抄送: Yuhang Zhao ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[wangwenx190/framelesshelper] 设置较小的边框高度后，窗口全屏会导致顶端被剪切 (#77)





 
我测试了一下 Windows 平台的 examples/mainwindow 程序，确实存在我提到的问题。注意截图中全屏模式下的左边界被剪切掉了一部分。
 

 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by altairwei** [comment]
这个问题在 `altairwei/2.0` 中已经修复。

问题的原因是：`Utilities::getSystemMetric` 函数新增了 `const bool dpiScale` 参数，但某些函数调用没有进行修复，导致参数 `const bool forceSystemValue = false` 采用了默认值。所以在去除 Windows 窗口边框时，`resizeBorderThickness` 获取到了用户设定值，而不是 Windows 系统的边框厚度。这就导致了用户在最大化时窗口被剪切掉一部分。

**Comment by wangwenx190** [comment]
原来是这里导致的问题。之前一直不知道是怎么回事。

**Comment by altairwei** [comment]
> 原来是这里导致的问题。之前一直不知道是怎么回事。

我们之前私聊时修复了这个问题，可能你忘了。我应该没有去修复 `1.x` 的代码。

**Comment by wangwenx190** [comment]
> > 原来是这里导致的问题。之前一直不知道是怎么回事。
> 
> 我们之前私聊时修复了这个问题，可能你忘了。我应该没有去修复 `1.x` 的代码。

也有可能。最近开的坑太多，东西都记不过来了。

**Comment by JulienMaille** [comment]
What about other calls like 
https://github.com/wangwenx190/framelesshelper/blob/9904a5077ada12e791807cae1571161b3035c1fe/framelesshelper_win32.cpp#L559-L560

**Comment by JulienMaille** [comment]
Also `2.0` still passes a single boolean
https://github.com/wangwenx190/framelesshelper/blob/f4d20e5f062c4dc12756202a295460310be4bdfd/src/core/framelesshelper_win32.cpp#L244

**Comment by wangwenx190** [comment]
> What about other calls like
> 
> https://github.com/wangwenx190/framelesshelper/blob/9904a5077ada12e791807cae1571161b3035c1fe/framelesshelper_win32.cpp#L559-L560

They are OK. The code there is used for determine the resize area of the window, so we should use the user's setted value if any. It's intended to be like that.

**Comment by wangwenx190** [comment]
> Also `2.0` still passes a single boolean
> 
> https://github.com/wangwenx190/framelesshelper/blob/f4d20e5f062c4dc12756202a295460310be4bdfd/src/core/framelesshelper_win32.cpp#L244

That file is not used by the 2.0 code. It was not deleted because the Qt Quick demo still need it. It will be removed once Qt Quick API is implemented in 2.0

**Comment by JulienMaille** [comment]
Thanks a lot

**Comment by wangwenx190** [comment]
For the 2.0 branch, the Qt Widgets API is mostly done now, if you want to develop cross-platform applications, you can try it (because the Windows part of the code is mostly the same with 1.x, so it's not necessary to use 2.0 code if you are only interested in Windows developing). For 2.0 we lowered the minimum required Qt version from 5.15 to 5.12, with complete support for macOS, Linux/X11 and Linux/Wayland. The Qt Quick API is still missing.
