### ISSUE TITLE
Purpose of the new 2.0 branches?

### ISSUE THREAD

**Issue by JulienMaille** [wangwenx190/framelesshelper#86]
Hello @altairwei and @wangwenx190 could you please tell me where I can find information on the different 2.0 branches that appeared in the past month? Is it a rewrite of the library? Is it Qt5 compatible?
Thanks in advance!

**Comment by altairwei** [comment]
We consider that the 1.x version of the borderless window on Linux and MacOS is a rudimentary implementation (arguably not yet implemented on MacOS) and relies on two APIs from Qt 5.15. So we intend to re-implement borderless windows on Linux and MacOS using the system native APIs and remove the dependency on those two Qt 5.15 APIs.

**Comment by JulienMaille** [comment]
Does it mean there's currently no reason to use 2.0 on Windows?
Thank you.

**Comment by wangwenx190** [comment]
>
> Is it a rewrite of the library?
>
For Linux and macOS, yes, the library is almost re-written. For Windows, no, no critical areas are touched, just minor refactoring to fit the new API design. For the current 1.x implementation, the Linux and macOS code are using QWindow's API which only available since Qt 5.15, and Qt's implementation on macOS is not completed due to the lacking of `QWindow::startSystemResize()`, the 2.0 code will use native code to do the move and resize stuff and thus the minimum required Qt version can be lowered from 5.15 to 5.6 and for macOS the missing support of window resizing will also be available. For Windows, the currrent 1.x implementation is stable enough, so we are not planning to make huge change to it.

>
> Is it Qt5 compatible?
>
Of course. This library will always support Qt 5 & Qt 6.

>
> the different 2.0 branches that appeared in the past month
>
You should consider @altairwei 's 2.0 branch is the next generation of this library. After some private discussions with @altairwei , I was convinced by him so I let him design the new API. The 2.0 branch created by me was then stopped developing and will be removed soon.

>
> Does it mean there's currently no reason to use 2.0 on Windows?
>
For now the 2.0 branch is still work-in-progress and it's not stable enough. The code is not finished yet and it needs more testing. When we think the 2.0 code is finished and stablizied we'll merge it into the main branch and delete the old 1.x branch. But it will not happen soon. And for Windows, the code actually doesn't change much, it will be refactored to fit the new architecture.
