### ISSUE TITLE
Bug when used with QGLWidget and overflown toolbar

### ISSUE THREAD

**Issue by JulienMaille** [wangwenx190/framelesshelper#97]
I have a very specific issue, which I only noticed this week but was present since March 2021.
This issue is triggered
 - when a toolbar does not have enough space to display all its buttons
 - when a `QGLWidget` is inserted in the `QMainWindow`
In that context, when you press the `>>` button and try to hover on the extra buttons, the toolbar will close as soon as the mouse is on top of the `QMainWindow`
![frameless](https://user-images.githubusercontent.com/182520/154146981-386e4040-0e7a-4df5-b0e6-c580fff7882e.gif)

EDIT: I know this is very specific, I tried to comment out bits of code until the bug is gone.
I'm still debugging with the code from March and this seems to be the infamous call:
```c++
void qCoreAppFixup()
{
    if (!QCoreApplication::testAttribute(Qt::AA_DontCreateNativeWidgetSiblings)) {
        QCoreApplication::setAttribute(Qt::AA_DontCreateNativeWidgetSiblings);
    }
}
```

**Comment by JulienMaille** [comment]
So one work around could be:
```c++
 for (QToolBar* tbar : findChildren<QToolBar*>())
    tbar->setAttribute(Qt::WA_NativeWindow);
```

**Comment by wangwenx190** [comment]
Really sorry for the delayed response. I somewhat missed or forgot about this issue, I apologize.

> I'm still debugging with the code from March and this seems to be the infamous call:

Does this block of code cause any issues? If so, it can be removed. This code was added because I read some commercial Qt components source code and some of them use that code to avoid some Qt bugs, but since I've never actually seen such bugs, the code may be unnecessary. If it's causing problems, it definitly should be removed.

> So one work around could be:

Make it a native window will cause it go through our native event filter, there will be some behavior change of course.

> However when doing so, the "window resizing area" is reduced when hovering on the toolbars

They now will go through our native event filter, so the resizing area is controlled by the event filter, the temporary solution is modify the logic of WM_NCHITTEST, but maybe should add a API for such situations.

**Comment by wangwenx190** [comment]
> I'm still debugging with the code from March

The code from 2021.03 ? It's really outdated, bro. There are many improvements since then. I suggest use or debug the latest code instead.

**Comment by JulienMaille** [comment]
Hello, The bug was present with latest code as well.
It actually forced me to port from `QGLVidget` to `QOpenGLWidget` so the issue is gone.
If your remove the `Qt::AA_DontCreateNativeWidgetSiblings` related code, then I get RTTI qWarning each time I maximize/restore the window.

**Comment by wangwenx190** [comment]
> It actually forced me to port from `QGLVidget` to `QOpenGLWidget` so the issue is gone.

It seems that `QGLWidget` is quite old and outdated and Qt official also recommends to migrate to the new `QOpenGLWidget`

**Comment by JulienMaille** [comment]
You're absolutely right. We can close this issue, maybe had a note in the Readme regarding  incomaptibility with QGLWidget

**Comment by wangwenx190** [comment]
> We can close this issue, maybe had a note in the Readme regarding incomaptibility with QGLWidget

OK. I'll update the README file and then close this issue.

**Comment by wangwenx190** [comment]
QGLWidget is not supported, closed. Feel free to reopen it if you think it's necessary.
